# Create src\esp32\ap_config.py for ESP32 AP preview mode.
Set-Location (Resolve-Path (Join-Path $PSScriptRoot "..\.."))

$example = Join-Path "src\esp32\ap_config.example.py"
$out = Join-Path "src\esp32\ap_config.py"

if (-not (Test-Path $example)) {
    Write-Error "Missing $example"
    exit 1
}

Write-Host "NomSpot AP mode config (ESP32 creates WiFi hotspot)"
Write-Host ""

$ssid = Read-Host "AP SSID [NomSpot-Cam]"
if (-not $ssid) { $ssid = "NomSpot-Cam" }

$password = Read-Host "AP password (>=8 chars) [12345678]"
if (-not $password) { $password = "12345678" }
if ($password.Length -lt 8) {
    Write-Error "Password must be at least 8 characters."
    exit 1
}

$channel = Read-Host "WiFi channel [6]"
if (-not $channel) { $channel = "6" }

$content = @"
# Generated by prepare_ap_config.ps1 — do not commit
AP_SSID = "$ssid"
AP_PASSWORD = "$password"
AP_CHANNEL = $channel
"@

$content | Set-Content -Path $out -Encoding utf8
Write-Host ""
Write-Host "Wrote $out"
Write-Host "Next: .\upload_ap.ps1 -Port COM4"
