# Create src\esp32\wifi_config.py for MVP (model laptop IP + home WiFi).
Set-Location (Resolve-Path (Join-Path $PSScriptRoot "..\.."))

$example = Join-Path "src\esp32\wifi_config.example.py"
$out = Join-Path "src\esp32\wifi_config.py"

if (-not (Test-Path $example)) {
    Write-Error "Missing $example"
    exit 1
}

$defaultIp = (
    Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object { $_.InterfaceAlias -notmatch 'Loopback' -and $_.IPAddress -notmatch '^169\.' } |
    Select-Object -First 1 -ExpandProperty IPAddress
)
if (-not $defaultIp) { $defaultIp = "192.168.1.100" }

Write-Host "NomSpot MVP — WiFi config for ESP32"
Write-Host "(Use the MODEL laptop IP if backend runs on another PC)"
Write-Host ""

$ssid = Read-Host "WiFi SSID"
$pass = Read-Host "WiFi password" -AsSecureString
$passPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($pass))
$ip = Read-Host "Model laptop IP [$defaultIp]"
if (-not $ip) { $ip = $defaultIp }

$content = @"
# Generated by prepare_wifi_config.ps1 — do not commit
SSID = "$ssid"
PASSWORD = "$passPlain"
BACKEND_URL = "http://${ip}:8000/api/frame"
UPLOAD_INTERVAL_S = 2
"@

$content | Set-Content -Path $out -Encoding utf8
Write-Host ""
Write-Host "Wrote $out"
Write-Host "Next: .\upload_wifi.ps1 -Port COM4"
